### PR TITLE
Export coprime_pairs

### PR DESCRIPTION
**Pull request by liangjs**

### CODE REVIEW

**Comment by liangjs** [comment]
How can we avoid forgetting to export functions?

**Comment by umutoztunc** [comment]
That is a good question. I guess we need to have some tests from the users perspective that tries to use the library but that would duplicate the test code. Also, we are still unsure how things will be used/imported. I guess we should try to detect it during code review by being more careful about it? It is like forgetting to mark things public, instead of having a test code or linter for it, I gues we should just notice it since it is a recurring theme. This is the second time that we forgot it and I feel like we will be more careful about it in the future already. I will try my best to think about things like "Are we going to make it public or private(internal)? If public, did we export it?"

What's your opinion about it before we merge and close this PR?

**Comment by liangjs** [comment]
How about moving the unit tests from number_theory to tql namespace?
Or we can write a check list for reviewers in a file like `review.md`.

**Comment by umutoztunc** [comment]
Interesting idea. That can work I think. Normally, I would say that tests should stay in their respective namespace since namespaces there to prevent name collisions. However, if we are going to export them in the end, they can still collide even if one function is defined in `number_theory` and other is defined in `graph_theory` since we are exporting both of them to the `tql` namespace.

We can discuss this further via private chat to not pollute this PR's comment section. I am merging this now.

**Review by umutoztunc — APPROVED** [review]

**Pull request merged**
