### PR TITLE
Add bit_length function

### PR DESCRIPTION
**Pull request by liangjs**
This provides the bit_length function.

### CODE REVIEW

**Review by umutoztunc — COMMENTED** [review]
What about using `__builtin_clz` instead of a while loop? Since the largest supported number type will be `long long`, we can take the difference between `numeric_limits<long long>::digits` and `__builtin_clzll` to calculate bit length.

NOTICE: The documentation says that `__builtin_clz` behaviour is undefined for 0. Locally, I tested it and it returns 32, 64 for int and long long zeros. However, we can just handle the case where the number is zero explicitly.

**Comment by umutoztunc** [comment]
Btw, I realized that `STL` already has template version of `__builtin_clz` as [countl_zero](https://en.cppreference.com/w/cpp/numeric/countl_zero). Maybe, we should use this one instead of the builtin functions.

**Comment by liangjs** [comment]
I rewrite the function with `std::countl_zero`.

**Review by umutoztunc — APPROVED** [review]
LGTM.

**Pull request merged**
